### Get all products
GET http://localhost:3000/products
Content-Type: application/json

###

### Seed sample products (optional)
POST http://localhost:3000/products/add
Content-Type: application/json

{
  "title": "TBATE",
  "price": 120,
  "image": "TBATE.jpg"
}
